CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_ZMK_EXT_POWER=y

# badjeff PMW3610-ALT driver
CONFIG_PMW3610_ALT=y

# Ориентация сенсора
# CONFIG_PMW3610_ALT_SWAP_XY - deprecated, используй swap-xy; в .overlay
# CONFIG_PMW3610_ALT_INVERT_X - deprecated, используй invert-x; в .overlay
# CONFIG_PMW3610_ALT_INVERT_Y - deprecated, используй invert-y; в .overlay

# Минимальный интервал отчетов (в мс)
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=12

# Smart algorithm для улучшенного отслеживания на разных поверхностях
# CONFIG_PMW3610_ALT_SMART_ALGORITHM=y

# Дополнительная задержка при инициализации (nice_nano_v2 fix)
CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=300

# Отладка
# CONFIG_PMW3610_ALT_LOG_LEVEL_DBG=y
